[toolchain]
anchor_version = "0.30.0"
[features]
resolution = true
skip-lint = false
[workspace]
members = ["programs/nft_escrow"]
[programs.devnet]
nft_escrow = "CDrWxJK6t2cLsCp7RjB6jiEVx2z5v8DUxxo7FfeBi4tW"
[registry]
url = "https://api.apr.dev"
[provider]
cluster = "https://api.devnet.solana.com"
wallet  = "C:\\Users\\Ryuk\\.config\\solana\\id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

